version: '3.9'

services:
  db:
    image: postgres
    restart: always
    shm_size: 128mb
    volumes:
      - type: tmpfs
        target: /dev/shm
        tmpfs:
          size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: book_db
      POSTGRES_USER: postgres
    ports:
      - "5433:5432"