server:
  port: 9000

spring:
  main:
    web-application-type: reactive
    allow-bean-definition-overriding: true
  application:
    name: gateway

  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: gateway
            client-secret: rl9TNIKMBzsSS5UbE2vPVYSMoZSE42IK
            scope: openid, profile, roles
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/bookstore/protocol/openid-connect/certs

  cloud:
    gateway:
      routes:
        - id: ms-user
          uri: http://localhost:8081
          predicates:
            - Path=/user/**
          filters:
            - TokenRelay
        - id: ms-book
          uri: http://localhost:8082
          predicates:
            - Path=/book/**
          filters:
            - TokenRelay
        - id: ms-transaction
          uri: http://localhost:8083
          predicates:
            - Path=/transaction/**
          filters:
            - TokenRelay
        - id: ms-email
          uri: http://localhost:8084
          predicates:
            - Path=/email/**
          filters:
            - TokenRelay
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    defaultZone: http://localhost:8761/eureka

logging:
  level:
    org:
      springframework:
        security: DEBUG
