server:
  port: 8083
  servlet:
    context-path: /transaction

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/gateway
  application:
    name: ms-transaction
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5435/transaction_db
    username: postgres
    password: Guga1957!
  jpa:
    hibernate:
      ddl-auto: update
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin
    virtual-host: /
    queue:
      name: email
    exchange:
      name: emailExchange
    routing-key:
      name: emailRoutingKey

feign:
  books:
    name: books
    url: http://localhost:8082/book/v1/book
  users:
    name: users
    url: http://localhost:8081/user/v1/users

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    defaultZone: http://localhost:8761/eureka
