server:
  port: 8081
  servlet:
    context-path: /user

spring:
  application:
    name: ms-user
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/gateway
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/user_db
    username: postgres
    password: Guga1957!
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update

api:
  security:
    token:
      secret: secret-key-authentication

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    defaultZone: http://localhost:8761/eureka